CREATE TABLE cart_items (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cart_id      BIGINT         NOT NULL,
    product_id   BIGINT         NOT NULL,
    quantity     INT            NOT NULL,
    unit_price   NUMERIC(12, 2) NOT NULL,
    currency     CHAR(3)        NOT NULL,
    product_name VARCHAR(200)   NOT NULL,
    snapshot_at  TIMESTAMPTZ    NOT NULL DEFAULT now(),
    created_at   TIMESTAMPTZ    NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ    NOT NULL DEFAULT now(),
    CONSTRAINT fk_cart_items_cart FOREIGN KEY (cart_id) REFERENCES carts (id) ON DELETE CASCADE,
    CONSTRAINT uq_cart_items_cart_product UNIQUE (cart_id, product_id),
    CONSTRAINT chk_cart_items_quantity CHECK (quantity BETWEEN 1 AND 100),
    CONSTRAINT chk_cart_items_unit_price_non_negative CHECK (unit_price >= 0)
);

CREATE INDEX idx_cart_items_cart_id ON cart_items (cart_id);
CREATE INDEX idx_cart_items_product_id ON cart_items (product_id);
