CREATE TABLE products (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku               VARCHAR(64)    NOT NULL,
    name              VARCHAR(200)   NOT NULL,
    description       TEXT,
    price             NUMERIC(12, 2) NOT NULL,
    currency          CHAR(3)        NOT NULL DEFAULT 'EUR',
    category_id       BIGINT         NOT NULL,
    stock_quantity    INT            NOT NULL DEFAULT 0,
    reserved_quantity INT            NOT NULL DEFAULT 0,
    deleted_at        TIMESTAMPTZ,
    created_at        TIMESTAMPTZ    NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ    NOT NULL DEFAULT now(),
    CONSTRAINT uq_products_sku UNIQUE (sku),
    CONSTRAINT fk_products_category FOREIGN KEY (category_id) REFERENCES categories (id),
    CONSTRAINT chk_products_price_non_negative CHECK (price >= 0),
    CONSTRAINT chk_products_stock_non_negative CHECK (stock_quantity >= 0),
    CONSTRAINT chk_products_reserved_non_negative CHECK (reserved_quantity >= 0)
);

CREATE INDEX idx_products_sku ON products (sku);
CREATE INDEX idx_products_name ON products (name);
CREATE INDEX idx_products_category_id ON products (category_id);
