CREATE TABLE stock_reservations (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id    UUID         NOT NULL,
    product_id  BIGINT       NOT NULL,
    quantity    INT          NOT NULL,
    status      VARCHAR(20)  NOT NULL,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_stock_reservations_order_product UNIQUE (order_id, product_id),
    CONSTRAINT fk_stock_reservations_product FOREIGN KEY (product_id) REFERENCES products (id),
    CONSTRAINT chk_stock_reservations_quantity_positive CHECK (quantity > 0),
    CONSTRAINT chk_stock_reservations_status CHECK (status IN ('RESERVED', 'RELEASED'))
);

CREATE INDEX idx_stock_reservations_order_id ON stock_reservations (order_id);
CREATE INDEX idx_stock_reservations_product_id ON stock_reservations (product_id);
